#!/bin/sh
#
# Startup script for xrd_storage_probe
#
# chkconfig: 345 85 15
# description: Gratia storage accounting for an Xrootd SE
# processname: xrd_storage_probe
# pidfile: /opt/vdt/gratia/var/tmp/xrd_storage_probe.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Some Gratia-specific additions
# The below line is properly set for a Pacman/VDT install.
VDT_LOCATION=MAGIC_VDT_LOCATION
# Fallback to default VDT location if this was an RPM-based install
[ -d $VDT_LOCATION ] || VDT_LOCATION=/opt/vdt

# The following adds the xrootd storage probe to the PATH.
PATH=$PATH:$VDT_LOCATION/gratia/probe/xrootd-storage
export VDT_LOCATION=$VDT_LOCATION

export HOME=/

case "$1" in
  start)
        echo -n "Starting  xrd_storage_probe: "
        daemon --pidfile $VDT_LOCATION/gratia/var/tmp/xrd_storage_probe.pid xrd_storage_probe -d
        echo
        touch /var/lock/subsys/xrd_storage_probe
        ;;
  stop)
        echo -n "Shutting down xrd_storage_probe: "
        killproc -p $VDT_LOCATION/gratia/var/tmp/xrd_storage_probe.pid xrd_storage_probe -INT
        sleep 1
        echo
        rm -f /var/lock/subsys/xrd_storage_probe
        ;;
  status)
        status -p $VDT_LOCATION/gratia/var/tmp/xrd_storage_probe.pid xrd_storage_probe
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
