<ProbeConfiguration

    Title1="Collector Information"

    CollectorHost="fermicloud049.fnal.gov:8880"
    SSLHost="fermicloud049.fnal.gov:8443"
    SSLRegistrationHost="fermicloud049.fnal.gov:8880"

    CollectorService="/gratia-servlets/rmi"
    SSLCollectorService="/gratia-servlets/rmi"
    RegistrationService="/gratia-registration/register"

    Title2="Probe information and functional configuration"

    ProbeName="lsf:fermicloud000.fnal.gov"
    SiteName="TestSite"
    Grid="ITB"
    SuppressUnknownVORecords="0"
    SuppressNoDNRecords="0"
    SuppressGridLocalRecords="0"
    QuarantineUnknownVORecords="1"
    EnableProbe="0"

    LsfVersion="LSF version"
      Comments21="This can be used if the lsf rpm commands fail to identify the version, leave empty otherwise"
    DataFile="/opt/workdir/lsb.acct.all"
    DataDirectory=""
      Comments22="You can specify the LSF accounting files or the directory where multiple accounting files are located"
    DefaultDomainName="my.domain"
      Comments23="Used when hostname is not returning the domain"

    Title3="Tuning parameter"

    BundleSize="100"
    MaxPendingFiles="100000"
    MaxStagedArchives="400"
    UseSyslog="0"
    ConnectionTimeout="900"

    LogLevel="5"
       Comments32="Controls debug messages printed to log file."
    DebugLevel="5"
       Comments33="Controls debug messages printed to screen."
    LogRotate="31"
    DataFileExpiration="31"
       Comments34="The number of days quarantined and unusable data files are kept"
    QuarantineSize="200"
       Comments35="The maximum size in Mb allowed to be kept in each quarantined directory"
    GratiaExtension="gratia.xml"

    Title4="Authentication Configuration"

    UseSSL="0"
    CertificateFile="/etc/grid-security/hostcert.pem"
    KeyFile="/etc/grid-security/hostkey.pem"
    UseGratiaCertificates="0"
       Comments40="If no directory is specified the gratia certificate file will be created in 'WorkingFolder'/certs."
    GratiaCertificateFile="/var/lib/gratia/data/certs/gratia.probecert.pem"
    GratiaKeyFile="/var/lib/gratia/data/certs/gratia.probekey.pem"

    Title5="File and directory location"

    UserVOMapFile="/var/lib/osg/user-vo-map"
        Comments51="Location and wildcard pattern of log files that contains certificate information about the jobs in the format followed by the 'blah demons'."
    CertInfoLogPattern="/var/log/accounting/blahp.log-*"
    CondorCEHistoryFolder="/var/lib/gratia/condorce_data"

    DataFolder="/var/lib/gratia/data/"
    WorkingFolder="/var/lib/gratia/tmp"
    LogFolder2="/var/log/gratia"
    LogFolder="./"

    Summarize="0"
    UpdateFrequency="120"
    StopFileName="stopGratiaFeed"
    ServerHost="BILLING_HOST"
    EmailServerHost="localhost"
    EmailFromAddress="lsf@localhost"
    EmailToList=""
    AggrLogLevel="warn"

/>
