#!/bin/sh
#
# Startup script for xrd_transfer_probe
#
# chkconfig: 345 85 15
# description: Gratia storage accounting for an Xrootd SE
# processname: xrd_transfer_probe
# pidfile: /var/run/xrd_transfer_probe.pid

# Source function library.
. /etc/rc.d/init.d/functions

# The following adds the xrootd storage probe to the PATH.
PATH=$PATH:/usr/share/gratia/xrootd-transfer

RETVAL=0

case "$1" in
  start)
        echo -n "Starting xrd_transfer_probe: "
        daemon xrd_transfer_probe -d -r 10
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/xrd_transfer_probe
        ;;
  stop)
        echo -n "Shutting down xrd_transfer_probe: "
        killproc xrd_transfer_probe -INT
        RETVAL=$?
        sleep 1
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/xrd_transfer_probe
        ;;
  status)
        status xrd_transfer_probe
        RETVAL=$?
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL

